WIP: tenant id
Azure/autorest.csharp pull request #1037
Opened 2021-02-18 03:33 UTC by bquantump

will be cleaner when #1032 closes

2021-02-18 16:19 UTC, chamons commented
I would like to suggest a different workflow if you don't need the draft PR features (thoughts @pakrym ?)

You can push to a branch on a fork and preview the PR without opening it. Then once it's ready for someone to look at, open the draft or "real" PR.

The "problem" is we're getting review notification spam on each PR commit being pushed, when it isn't obvious that when you want an actual review.

2021-02-18 16:22 UTC, pakrym commented
Strangely https://github.blog/changelog/2019-02-14-draft-pull-requests/

states:

>. Draft pull requests suppress notifications to CODEOWNERS reviewers and cannot be merged until they are marked as “Ready for review” in the merge box.

But it seems it doesn't

2021-02-18 16:40 UTC, chamons commented
Agreed - very strange (and buggy?).

2021-02-19 01:38 UTC, m-nash commented
We don't get the benefit of seeing the CI checks if we don't open draft to a branch named feature/* in this fork

2021-02-19 01:47 UTC, m-nash requested changes

2021-02-19 01:47 UTC, m-nash commented on src/AutoRest.CSharp/Input/CodeModelPartials.cs
> +
extra lines

2021-02-19 01:47 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Requests/ProviderToken.cs
> +}
missing newline

2021-02-19 01:47 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Requests/ProviderToken.cs
> +        internal bool noPredecessor;
Make these properties with appropriate get / set and PascalCase

2021-02-19 01:47 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Requests/ProviderToken.cs
> +            noPredecessor = false;
no need to initialize if its the default value

2021-02-19 01:47 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Types/OutputLibrary.cs
> +        public static List<ProviderToken> Tokenize(string path)
I feel like this method and MakeTokens belong to a different class that OutputLibrary can use

2021-02-19 22:30 UTC, m-nash requested changes

2021-02-19 22:30 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Types/OutputLibrary.cs
> +        public bool IsTenantOnly(OperationGroup operationGroup)
Can we move this to a TenantDetection class?

2021-02-19 22:30 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Types/OutputLibrary.cs
> +        public static List<ProviderSegment> GetProviderSegments(string path)
Can we move this to a ProviderSegmentDetection class?

2021-02-19 22:32 UTC, m-nash requested changes

2021-02-19 22:32 UTC, m-nash commented on src/AutoRest.CSharp/Output/Models/Types/OutputLibrary.cs
> +        public bool VerifyOperation(string tokenValue, string resourceType)
weren't we going to remove this?

2021-02-22 18:39 UTC, m-nash approved these changes

2021-02-22 18:39 UTC, merged