nibhati-5779-add ResourceIdentifier
Azure/autorest.csharp pull request #1225
Opened 2021-05-07 21:46 UTC by nisha-bhatia

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [x] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

2021-05-07 21:47 UTC, nisha-bhatia commented
ADO item: https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_boards/board/t/DotNET%20Management%20SDK%20Team/Stories/?workitem=5779

2021-05-07 22:14 UTC, m-nash requested changes

2021-05-07 22:14 UTC, m-nash commented on test/TestProjects/OperationGroupMappings/OperationGroupMappings.sln
> +﻿
remove this file

2021-05-10 16:41 UTC, chamons commented
The tl;dr diff - https://gist.github.com/ea72d5c53c8cde4b388c38dc91b07533

2021-05-10 16:58 UTC, m-nash approved these changes

2021-05-10 17:08 UTC, pakrym commented on src/AutoRest.CSharp/Common/Output/Models/Types/SystemObjectType.cs
> +        protected override string DefaultNamespace => _type.Namespace ?? base.DefaultNamespace;
is `_type.Namespace` ever null?

2021-05-10 17:20 UTC, merged

2021-05-10 18:28 UTC, nisha-bhatia commented
_type.Namespace can be null, as the type for Namespace in the Type class is string?

2021-05-10 18:36 UTC, pakrym commented
I don't think the base.DefaultNamespace would be the right thing to use in that case anyway.