Udpate LRO pattern to use new SLRO
Azure/autorest.csharp pull request #1473
Opened 2021-08-18 20:34 UTC by ShivangiReja

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

2021-08-18 22:43 UTC, allenjzhang commented on samples/Azure.Management.Storage/Generated/BlobContainer.cs
> +        public virtual BlobContainerDeleteOperation Delete(bool waitForCompletion = true, CancellationToken cancellationToken = default)
>Delete [](http://example.com/codeflow?start=52&length=6)

Response<BlobContainerDeleteOperation>?

2021-08-19 00:44 UTC, allenjzhang commented
>                 WriteClientMethod(_writer, restMethod, restMethod.Name, _resourceContainer.GetDiagnostic(restMethod.RestClientMethod), _resourceContainer.OperationGroup, _context, true);

is LRO respected for RemainingMethods?

---
Refers to: src/AutoRest.CSharp/Mgmt/Generation/ResourceContainerWriter.cs:104 in 1a7744b. [](commit_id = 1a7744b9ae4ab93f8cee160d385fe8732ec6e437, deletion_comment = False)

2021-08-19 02:06 UTC, ShivangiReja reviewed
Test

2021-08-19 16:55 UTC, allenjzhang commented on src/AutoRest.CSharp/Mgmt/AutoRest/MgmtOutputLibrary.cs
> +            return clientMethod.Operation.IsLongRunningReallyLong != null ? clientMethod.Operation.IsLongRunningReallyLong.Value : false;
nit: return clientMethod.Operation.IsLongRunningReallyLong??false;

2021-08-19 17:04 UTC, allenjzhang commented
>             "post": {

Can we add a S/LRO post operation? One real example is VM poweroff.

---
Refers to: test/TestProjects/MgmtLRO/mgmtLRO.json:284 in 1a7744b. [](commit_id = 1a7744b9ae4ab93f8cee160d385fe8732ec6e437, deletion_comment = False)

2021-08-19 17:13 UTC, allenjzhang requested changes
Once we have examples of LRO and SLRO for post operations, I am good to merge the PR.

2021-08-19 19:07 UTC, allenjzhang approved these changes

2021-08-19 19:07 UTC, merged