[Mgmt] Expand enum in resource types
Azure/autorest.csharp pull request #1711
Opened 2021-11-22 11:01 UTC by ArcturusZhang

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

2021-12-20 22:39 UTC, m-nash requested changes

2021-12-20 22:39 UTC, m-nash commented on src/AutoRest.CSharp/Mgmt/AutoRest/MgmtOutputLibrary.cs
> +        private Dictionary<string, Dictionary<ResourceType, Resource>>? _rawRequestPathToArmResource;
Lets discuss this, its not intuitive why all of these types need a dictionary now and I wonder if there is a more clear way to represent this

2021-12-20 22:39 UTC, m-nash commented on src/AutoRest.CSharp/Mgmt/Output/MgmtLongRunningOperation.cs
> +                WrapperType = context.Library.GetArmResources(operation.GetHttpPath()).First().Type;
is First always safe always?

2021-12-22 14:50 UTC, ArcturusZhang commented
/azp run autorest.csharp - ci

2021-12-23 02:23 UTC, m-nash approved these changes

2021-12-23 07:29 UTC, ArthurMa1978 approved these changes

2021-12-24 07:53 UTC, merged