Throw exception when patch operation has an optional body parameter
Azure/autorest.csharp pull request #1975
Opened 2022-02-14 10:00 UTC by ArcturusZhang

Fixes https://github.com/Azure/autorest.csharp/issues/1968

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

2022-02-15 20:17 UTC, AlexanderSher requested changes
Blocking this one until we have an archboard decision about required body in PATCH and PUT
cc @m-nash @annelo-msft @tg-msft @JeffreyRichter

2022-02-23 23:40 UTC, AlexanderSher approved these changes
Null-checks for PATCH body parameter has been approved.

2022-03-02 09:02 UTC, ArcturusZhang commented
Please preview the changes of this PR here: https://github.com/Azure/azure-sdk-for-net/pull/27299/files

2022-03-08 03:03 UTC, fengzhou-msft commented on test/TestProjects/MgmtDiscriminator/MgmtDiscriminator.json
> +                    "format": "duration",
```suggestion
                    "format": "duration",
                    "x-ms-format": "duration-constant"
```
Based on the description, it's using the constant format not the default period format.

2022-03-08 03:35 UTC, merged